/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/EditSong`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/ChangePassword` | `/ChangePassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(presentation)'}/Presentation` | `/Presentation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ChordLibrary` | `/ChordLibrary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Metronome` | `/Metronome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Plus` | `/Plus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Songlist` | `/Songlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Tuner` | `/Tuner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/User` | `/User`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/EditSong`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/ChangePassword` | `/ChangePassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(presentation)'}/Presentation` | `/Presentation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ChordLibrary` | `/ChordLibrary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Metronome` | `/Metronome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Plus` | `/Plus`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Songlist` | `/Songlist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Tuner` | `/Tuner`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/User` | `/User`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/EditSong${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/ChangePassword${`?${string}` | `#${string}` | ''}` | `/ChangePassword${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `${'/(presentation)'}/Presentation${`?${string}` | `#${string}` | ''}` | `/Presentation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ChordLibrary${`?${string}` | `#${string}` | ''}` | `/ChordLibrary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Metronome${`?${string}` | `#${string}` | ''}` | `/Metronome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Plus${`?${string}` | `#${string}` | ''}` | `/Plus${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Songlist${`?${string}` | `#${string}` | ''}` | `/Songlist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Tuner${`?${string}` | `#${string}` | ''}` | `/Tuner${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/User${`?${string}` | `#${string}` | ''}` | `/User${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/EditSong`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/ChangePassword` | `/ChangePassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(presentation)'}/Presentation` | `/Presentation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ChordLibrary` | `/ChordLibrary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Metronome` | `/Metronome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Plus` | `/Plus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Songlist` | `/Songlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Tuner` | `/Tuner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/User` | `/User`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
