

services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  node:
    image: node:latest
    container_name: node_api_container
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    environment:
      PYTHON_API_URL: http://python:8000
    networks:
      - app-network
    depends_on:
      - python

  python:
    image: python:latest
    container_name: python_scraper_container
    working_dir: /usr/src/app
    volumes:
      - ./python:/usr/src/app
    ports:
      - "8000:8000"
    command: sh -c "pip install -r requirements.txt && python scrapper.py"
    environment:
      MONGO_URI: mongodb://root:example@db:27017/admin
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge