const FAKEDATA = [
  {
    id: 1,
    Song: "Snow",
    Artist: "Red Hot Chilli Peppers",
    Progression: 14,
    Instruments: {
      guitar01: true,
      guitar02: false,
      bass: true,
      Keys: true,
      Drums: false,
      Voice: true,
    },
  },
  {
    id: 2,
    Song: "Enter Sandman",
    Artist: "Metallica",
    Progression: 30,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: false,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 3,
    Song: "Bohemian Rhapsody",
    Artist: "Queen",
    Progression: 50,
    Instruments: {
      guitar01: true,
      guitar02: false,
      bass: true,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 4,
    Song: "Hotel California",
    Artist: "Eagles",
    Progression: 65,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 5,
    Song: "Sweet Child O' Mine",
    Artist: "Guns N' Roses",
    Progression: 45,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: false,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 6,
    Song: "Stairway to Heaven",
    Artist: "Led Zeppelin",
    Progression: 75,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 7,
    Song: "Back in Black",
    Artist: "AC/DC",
    Progression: 40,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: false,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 8,
    Song: "Imagine",
    Artist: "John Lennon",
    Progression: 55,
    Instruments: {
      guitar01: false,
      guitar02: false,
      bass: false,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 9,
    Song: "Smells Like Teen Spirit",
    Artist: "Nirvana",
    Progression: 60,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: false,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 10,
    Song: "Comfortably Numb",
    Artist: "Pink Floyd",
    Progression: 70,
    Instruments: {
      guitar01: true,
      guitar02: true,
      bass: true,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
  {
    id: 11,
    Song: "One",
    Artist: "U2",
    Progression: 32,
    Instruments: {
      guitar01: true,
      guitar02: false,
      bass: true,
      Keys: true,
      Drums: true,
      Voice: true,
    },
  },
];
export default FAKEDATA;
