export const PersonalChordLibrary = [
  // C Chords
  {
    strings: "X 3 2 0 1 0",
    fingering: "X 3 2 0 1 0",
    chordName: "C,,,",
    root: "C",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard C major chord.",
  },
  {
    strings: "X 3 1 0 1 3",
    fingering: "X 3 1 0 2 4",
    chordName: "C,,7,",
    root: "C",
    quality: "",
    tension: "7",
    bass: "",
    description: "C7 chord, standard open position.",
  },
  {
    strings: "X 3 2 0 0 0",
    fingering: "X 3 2 0 0 0",
    chordName: "C,maj,7,",
    root: "C",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Cmaj7 chord, open position.",
  },
  {
    strings: "X 3 1 0 1 0",
    fingering: "X 3 1 0 2 0",
    chordName: "C,m,,",
    root: "C",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard C minor chord.",
  },
  {
    strings: "X 3 1 0 1 3",
    fingering: "X 3 1 0 2 4",
    chordName: "C,m,7,",
    root: "C",
    quality: "m",
    tension: "7",
    bass: "",
    description: "C minor 7th chord.",
  },
  {
    strings: "X 3 0 0 1 0",
    fingering: "X 2 0 0 1 0",
    chordName: "C,,add9,",
    root: "C",
    quality: "",
    tension: "add9",
    bass: "",
    description: "C add9 chord.",
  },
  {
    strings: "8 10 10 9 8 8",
    fingering: "1 3 4 2 1 1",
    chordName: "C,,,",
    root: "C",
    quality: "",
    tension: "",
    bass: "C",
    description: "C major barre chord at the 8th fret with C as bass.",
  },
  {
    strings: "8 10 10 8 8 8",
    fingering: "1 3 4 1 1 1",
    chordName: "C,m,,",
    root: "C",
    quality: "m",
    tension: "",
    bass: "C",
    description: "C minor barre chord at the 8th fret with C as bass.",
  },
  {
    strings: "X 3 2 3 1 3",
    fingering: "X 3 2 4 1 4",
    chordName: "C,,9,",
    root: "C",
    quality: "",
    tension: "9",
    bass: "",
    description: "C9 chord.",
  },
  {
    strings: "X 3 5 5 5 3",
    fingering: "X 1 3 4 4 1",
    chordName: "C,,,G",
    root: "C",
    quality: "",
    tension: "",
    bass: "G",
    description: "C major chord with G as bass.",
  },
  {
    strings: "X 3 5 3 5 3",
    fingering: "X 1 3 1 4 1",
    chordName: "C,,7,G",
    root: "C",
    quality: "",
    tension: "7",
    bass: "G",
    description: "C7 chord with G as bass.",
  },
  {
    strings: "8 10 8 9 8 8",
    fingering: "1 3 1 2 1 1",
    chordName: "C,maj,7,E",
    root: "C",
    quality: "maj",
    tension: "7",
    bass: "E",
    description: "Cmaj7 chord with E as bass.",
  },
  {
    strings: "X 3 5 3 4 3",
    fingering: "X 1 3 1 2 1",
    chordName: "C,m,7,Bb",
    root: "C",
    quality: "m",
    tension: "7",
    bass: "Bb",
    description: "C minor 7th chord with Bb as bass.",
  },
  {
    strings: "X 3 3 2 1 1",
    fingering: "X 3 3 2 1 1",
    chordName: "C,m,7b5,E",
    root: "C",
    quality: "m",
    tension: "7b5",
    bass: "E",
    description: "C minor 7th flat 5 chord with E as bass.",
  },
  {
    strings: "X 3 5 5 4 3",
    fingering: "X 1 3 4 2 1",
    chordName: "C,,7/9,A",
    root: "C",
    quality: "",
    tension: "7/9",
    bass: "A",
    description: "C7/9 chord with A as bass.",
  },
  {
    strings: "X 3 5 5 5 5",
    fingering: "X 1 3 3 3 3",
    chordName: "C,,7sus4,F",
    root: "C",
    quality: "",
    tension: "7sus4",
    bass: "F",
    description: "C7sus4 chord with F as bass.",
  },
  {
    strings: "X 3 2 3 3 3",
    fingering: "X 2 1 3 3 3",
    chordName: "C,,add11,D",
    root: "C",
    quality: "",
    tension: "add11",
    bass: "D",
    description: "C add11 chord with D as bass.",
  },
  {
    strings: "X 3 3 0 1 1",
    fingering: "X 2 3 0 1 1",
    chordName: "C,maj,7b5,F#",
    root: "C",
    quality: "maj",
    tension: "7b5",
    bass: "F#",
    description: "Cmaj7 chord with flat fifth and F# as bass.",
  },
  {
    strings: "X 3 5 5 4 3",
    fingering: "X 1 3 4 2 1",
    chordName: "C,m,6/9,G",
    root: "C",
    quality: "m",
    tension: "6/9",
    bass: "G",
    description: "C minor 6/9 chord with G as bass.",
  },

  // C# Chords
  {
    strings: "X 4 6 6 6 4",
    fingering: "X 1 3 4 4 1",
    chordName: "C#,,,",
    root: "C#",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard C# major barre chord.",
  },
  {
    strings: "X 4 6 6 5 4",
    fingering: "X 1 3 4 2 1",
    chordName: "C#,m,,",
    root: "C#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard C# minor barre chord.",
  },
  {
    strings: "X 4 6 4 6 4",
    fingering: "X 1 3 1 4 1",
    chordName: "C#,,7,",
    root: "C#",
    quality: "",
    tension: "7",
    bass: "",
    description: "C#7 chord with barre shape.",
  },
  {
    strings: "X 4 3 1 2 1",
    fingering: "X 4 3 1 2 1",
    chordName: "C#,m,7,",
    root: "C#",
    quality: "m",
    tension: "7",
    bass: "",
    description: "C#m7 chord with alternative voicing.",
  },
  {
    strings: "X 4 6 5 6 4",
    fingering: "X 1 3 2 4 1",
    chordName: "C#,maj,7,",
    root: "C#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "C#maj7 chord with barre shape.",
  },
  {
    strings: "X 4 1 1 2 1",
    fingering: "X 4 1 1 2 1",
    chordName: "C#,m,,",
    root: "C#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Alternative C#m chord voicing.",
  },
  {
    strings: "X 4 6 6 5 4",
    fingering: "X 1 3 4 2 1",
    chordName: "C#,m,,G#",
    root: "C#",
    quality: "m",
    tension: "",
    bass: "G#",
    description: "C#m chord with G# as bass.",
  },
  {
    strings: "9 11 11 10 9 9",
    fingering: "1 3 4 2 1 1",
    chordName: "C#,,,C#",
    root: "C#",
    quality: "",
    tension: "",
    bass: "C#",
    description: "C# major barre chord at 9th fret.",
  },
  {
    strings: "X 4 6 4 5 4",
    fingering: "X 1 3 1 2 1",
    chordName: "C#,m,7,F#",
    root: "C#",
    quality: "m",
    tension: "7",
    bass: "F#",
    description: "C#m7 chord with F# as bass.",
  },
  {
    strings: "X 4 6 4 6 4",
    fingering: "X 1 3 1 4 1",
    chordName: "C#,,7,A#",
    root: "C#",
    quality: "",
    tension: "7",
    bass: "A#",
    description: "C#7 chord with A# as bass.",
  },
  {
    strings: "X 4 6 6 6 6",
    fingering: "X 1 3 3 3 3",
    chordName: "C#,,7sus4,G#",
    root: "C#",
    quality: "",
    tension: "7sus4",
    bass: "G#",
    description: "C#7sus4 chord with G# as bass.",
  },
  {
    strings: "X 4 3 3 2 1",
    fingering: "X 4 3 3 2 1",
    chordName: "C#,m,7,E",
    root: "C#",
    quality: "m",
    tension: "7",
    bass: "E",
    description: "C#m7 chord with E as bass.",
  },
  {
    strings: "X 4 3 1 2 1",
    fingering: "X 4 3 1 2 1",
    chordName: "C#,m,7b5,G",
    root: "C#",
    quality: "m",
    tension: "7b5",
    bass: "G",
    description: "C#m7b5 chord with G as bass.",
  },
  {
    strings: "X 4 6 6 5 4",
    fingering: "X 1 3 4 2 1",
    chordName: "C#,m,6/9,F#",
    root: "C#",
    quality: "m",
    tension: "6/9",
    bass: "F#",
    description: "C#m6/9 chord with F# as bass.",
  },
  {
    strings: "X 4 4 6 4 6",
    fingering: "X 1 1 3 1 4",
    chordName: "C#,,add11,B",
    root: "C#",
    quality: "",
    tension: "add11",
    bass: "B",
    description: "C# add11 chord with B as bass.",
  },
  {
    strings: "9 11 11 9 9 9",
    fingering: "1 3 4 1 1 1",
    chordName: "C#,m,,C#",
    root: "C#",
    quality: "m",
    tension: "",
    bass: "C#",
    description: "C#m barre chord at 9th fret with C# as bass.",
  },
  {
    strings: "X 4 1 1 2 1",
    fingering: "X 4 1 1 2 1",
    chordName: "C#,m,,G#",
    root: "C#",
    quality: "m",
    tension: "",
    bass: "G#",
    description: "C#m chord with G# as bass.",
  },
  {
    strings: "9 11 9 10 9 9",
    fingering: "1 3 1 2 1 1",
    chordName: "C#,maj,7,F",
    root: "C#",
    quality: "maj",
    tension: "7",
    bass: "F",
    description: "C#maj7 chord with F as bass.",
  },
  {
    strings: "X 4 6 5 6 4",
    fingering: "X 1 3 2 4 1",
    chordName: "C#,maj,7b5,F#",
    root: "C#",
    quality: "maj",
    tension: "7b5",
    bass: "F#",
    description: "C#maj7 chord with flat fifth and F# as bass.",
  },
  {
    strings: "X 4 6 6 6 6",
    fingering: "X 1 3 3 3 3",
    chordName: "C#,,7sus4,A",
    root: "C#",
    quality: "",
    tension: "7sus4",
    bass: "A",
    description: "C#7sus4 chord with A as bass.",
  },

  // D Chords
  {
    strings: "X X 0 2 3 2",
    fingering: "X X 1 3 2 1",
    chordName: "D,,,",
    root: "D",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard D major chord.",
  },
  {
    strings: "X X 0 2 3 1",
    fingering: "X X 1 3 2 1",
    chordName: "D,m,,",
    root: "D",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard D minor chord.",
  },
  {
    strings: "X X 0 2 1 2",
    fingering: "X X 1 3 2 4",
    chordName: "D,,7,",
    root: "D",
    quality: "",
    tension: "7",
    bass: "",
    description: "D7 chord, standard open position.",
  },
  {
    strings: "X X 0 2 2 2",
    fingering: "X X 1 2 3 4",
    chordName: "D,maj,7,",
    root: "D",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "D major 7th chord.",
  },
  {
    strings: "X X 0 2 1 1",
    fingering: "X X 1 2 1 1",
    chordName: "D,m,7,",
    root: "D",
    quality: "m",
    tension: "7",
    bass: "",
    description: "D minor 7th chord.",
  },
  {
    strings: "X X 0 2 3 0",
    fingering: "X X 1 2 3 0",
    chordName: "D,,add9,",
    root: "D",
    quality: "",
    tension: "add9",
    bass: "",
    description: "D add9 chord.",
  },
  {
    strings: "X X 0 4 3 2",
    fingering: "X X 1 3 2 1",
    chordName: "D,maj,9,",
    root: "D",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "D major 9th chord.",
  },
  {
    strings: "X 5 7 7 7 5",
    fingering: "X 1 3 4 4 1",
    chordName: "D,,,A",
    root: "D",
    quality: "",
    tension: "",
    bass: "A",
    description: "D major barre chord with A as bass note.",
  },
  {
    strings: "X 5 7 7 6 5",
    fingering: "X 1 3 4 2 1",
    chordName: "D,m,,A",
    root: "D",
    quality: "m",
    tension: "",
    bass: "A",
    description: "D minor barre chord with A as bass note.",
  },
  {
    strings: "X X 0 2 1 3",
    fingering: "X X 1 2 1 4",
    chordName: "D,,7sus4,",
    root: "D",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "D7sus4 chord, open position.",
  },
  {
    strings: "X X 0 2 0 2",
    fingering: "X X 1 2 0 3",
    chordName: "D,,6,",
    root: "D",
    quality: "",
    tension: "6",
    bass: "",
    description: "D6 chord, open position.",
  },
  {
    strings: "10 12 12 11 10 10",
    fingering: "1 3 4 2 1 1",
    chordName: "D,,,D",
    root: "D",
    quality: "",
    tension: "",
    bass: "D",
    description: "D major barre chord, 10th fret position with D as bass.",
  },
  {
    strings: "10 12 12 10 10 10",
    fingering: "1 3 4 1 1 1",
    chordName: "D,m,,D",
    root: "D",
    quality: "m",
    tension: "",
    bass: "D",
    description: "D minor barre chord, 10th fret position with D as bass.",
  },
  {
    strings: "X X 0 2 4 4",
    fingering: "X X 1 2 4 4",
    chordName: "D,,6/9,",
    root: "D",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "D6/9 chord.",
  },
  {
    strings: "X 5 4 2 3 2",
    fingering: "X 4 3 1 2 1",
    chordName: "D,maj,7,",
    root: "D",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Dmaj7 chord with alternative voicing.",
  },
  {
    strings: "X X 0 2 0 3",
    fingering: "X X 1 2 0 4",
    chordName: "D,,add11,",
    root: "D",
    quality: "",
    tension: "add11",
    bass: "",
    description: "D chord with an added 11th.",
  },
  {
    strings: "X X 12 11 10 10",
    fingering: "X X 3 2 1 1",
    chordName: "D,m,,D#",
    root: "D",
    quality: "m",
    tension: "",
    bass: "D#",
    description: "D minor chord with high voicing and D# as bass.",
  },
  {
    strings: "X X 12 14 15 14",
    fingering: "X X 1 3 4 2",
    chordName: "D,,9,E",
    root: "D",
    quality: "",
    tension: "9",
    bass: "E",
    description: "D9 chord, high voicing with E as bass.",
  },
  {
    strings: "X 5 4 0 3 0",
    fingering: "X 4 3 0 2 0",
    chordName: "D,maj,7b5,G",
    root: "D",
    quality: "maj",
    tension: "7b5",
    bass: "G",
    description: "Dmaj7 chord with flat fifth and G as bass.",
  },
  {
    strings: "X X 0 2 4 5",
    fingering: "X X 1 2 4 5",
    chordName: "D,,6/9,A",
    root: "D",
    quality: "",
    tension: "6/9",
    bass: "A",
    description: "D6/9 chord with A as bass.",
  },

  // D# Chords
  {
    strings: "X 6 8 8 8 6",
    fingering: "X 1 3 4 4 1",
    chordName: "D#,,,",
    root: "D#",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard D# major barre chord.",
  },
  {
    strings: "X 6 8 8 7 6",
    fingering: "X 1 3 4 2 1",
    chordName: "D#,m,,",
    root: "D#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard D# minor barre chord.",
  },
  {
    strings: "X 6 8 6 8 6",
    fingering: "X 1 3 1 4 1",
    chordName: "D#,,7,",
    root: "D#",
    quality: "",
    tension: "7",
    bass: "",
    description: "D#7 chord with barre shape.",
  },
  {
    strings: "X 6 4 3 4 3",
    fingering: "X 4 1 2 3 2",
    chordName: "D#,m,7,",
    root: "D#",
    quality: "m",
    tension: "7",
    bass: "",
    description: "D#m7 chord with alternative voicing.",
  },
  {
    strings: "X 6 8 7 8 6",
    fingering: "X 1 3 2 4 1",
    chordName: "D#,maj,7,",
    root: "D#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "D#maj7 chord with barre shape.",
  },
  {
    strings: "X 6 8 6 7 6",
    fingering: "X 1 3 1 2 1",
    chordName: "D#,m,,A#",
    root: "D#",
    quality: "m",
    tension: "",
    bass: "A#",
    description: "D#m chord with A# as bass.",
  },
  {
    strings: "11 13 13 12 11 11",
    fingering: "1 3 4 2 1 1",
    chordName: "D#,,,D#",
    root: "D#",
    quality: "",
    tension: "",
    bass: "D#",
    description: "D# major barre chord at the 11th fret with D# as bass.",
  },
  {
    strings: "X 6 4 6 4 6",
    fingering: "X 1 2 3 2 4",
    chordName: "D#,m,7,G#",
    root: "D#",
    quality: "m",
    tension: "7",
    bass: "G#",
    description: "D#m7 chord with G# as bass.",
  },
  {
    strings: "X 6 8 6 8 6",
    fingering: "X 1 3 1 4 1",
    chordName: "D#,,7,C",
    root: "D#",
    quality: "",
    tension: "7",
    bass: "C",
    description: "D#7 chord with C as bass.",
  },
  {
    strings: "X 6 8 8 8 8",
    fingering: "X 1 3 3 3 3",
    chordName: "D#,,7sus4,G#",
    root: "D#",
    quality: "",
    tension: "7sus4",
    bass: "G#",
    description: "D#7sus4 chord with G# as bass.",
  },
  {
    strings: "X 6 5 3 4 3",
    fingering: "X 4 3 1 2 1",
    chordName: "D#,m,7,E",
    root: "D#",
    quality: "m",
    tension: "7",
    bass: "E",
    description: "D#m7 chord with E as bass.",
  },
  {
    strings: "X 6 5 3 4 3",
    fingering: "X 4 3 1 2 1",
    chordName: "D#,m,7b5,G",
    root: "D#",
    quality: "m",
    tension: "7b5",
    bass: "G",
    description: "D#m7b5 chord with G as bass.",
  },
  {
    strings: "X 6 8 8 7 6",
    fingering: "X 1 3 4 2 1",
    chordName: "D#,m,6/9,B",
    root: "D#",
    quality: "m",
    tension: "6/9",
    bass: "B",
    description: "D#m6/9 chord with B as bass.",
  },
  {
    strings: "X 6 5 6 4 6",
    fingering: "X 1 2 3 1 4",
    chordName: "D#,,add11,C#",
    root: "D#",
    quality: "",
    tension: "add11",
    bass: "C#",
    description: "D# add11 chord with C# as bass.",
  },
  {
    strings: "11 13 11 12 11 11",
    fingering: "1 3 1 2 1 1",
    chordName: "D#,maj,7,G",
    root: "D#",
    quality: "maj",
    tension: "7",
    bass: "G",
    description: "D#maj7 chord with G as bass.",
  },
  {
    strings: "X 6 8 7 8 6",
    fingering: "X 1 3 2 4 1",
    chordName: "D#,maj,7b5,F",
    root: "D#",
    quality: "maj",
    tension: "7b5",
    bass: "F",
    description: "D#maj7 chord with flat fifth and F as bass.",
  },
  {
    strings: "X 6 8 8 8 8",
    fingering: "X 1 3 3 3 3",
    chordName: "D#,,7sus4,A",
    root: "D#",
    quality: "",
    tension: "7sus4",
    bass: "A",
    description: "D#7sus4 chord with A as bass.",
  },

  // E Chords

  {
    strings: "0 2 2 1 0 0",
    fingering: "0 2 3 1 0 0",
    chordName: "E,,,",
    root: "E",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard E major chord.",
  },
  {
    strings: "0 2 2 0 0 0",
    fingering: "0 2 3 0 0 0",
    chordName: "E,m,,",
    root: "E",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard E minor chord.",
  },
  {
    strings: "0 2 0 1 0 0",
    fingering: "0 2 0 1 0 0",
    chordName: "E,,7,",
    root: "E",
    quality: "",
    tension: "7",
    bass: "",
    description: "E7 chord, open position.",
  },
  {
    strings: "0 2 1 1 0 0",
    fingering: "0 2 1 1 0 0",
    chordName: "E,maj,7,",
    root: "E",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "E major 7th chord.",
  },
  {
    strings: "0 2 0 0 0 0",
    fingering: "0 2 0 0 0 0",
    chordName: "E,,add9,",
    root: "E",
    quality: "",
    tension: "add9",
    bass: "",
    description: "E add9 chord.",
  },
  {
    strings: "0 2 4 1 0 0",
    fingering: "0 2 4 1 0 0",
    chordName: "E,maj,9,",
    root: "E",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "E major 9th chord.",
  },
  {
    strings: "0 2 2 1 3 0",
    fingering: "0 2 3 1 4 0",
    chordName: "E,,7sus4,",
    root: "E",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "E7sus4 chord, open position.",
  },
  {
    strings: "0 2 2 4 0 0",
    fingering: "0 1 2 4 0 0",
    chordName: "E,,6,",
    root: "E",
    quality: "",
    tension: "6",
    bass: "",
    description: "E6 chord, open position.",
  },
  {
    strings: "0 2 2 4 2 0",
    fingering: "0 1 2 4 3 0",
    chordName: "E,,6/9,",
    root: "E",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "E6/9 chord.",
  },
  {
    strings: "7 7 9 9 9 7",
    fingering: "1 1 3 3 3 1",
    chordName: "E,,,",
    root: "E",
    quality: "",
    tension: "",
    bass: "E",
    description: "E major barre chord at the 7th fret.",
  },
  {
    strings: "7 7 9 7 9 7",
    fingering: "1 1 3 1 4 1",
    chordName: "E,,7,E",
    root: "E",
    quality: "",
    tension: "7",
    bass: "E",
    description: "E7 chord with E as bass, 7th fret.",
  },
  {
    strings: "7 7 9 8 9 7",
    fingering: "1 1 3 2 4 1",
    chordName: "E,maj,7,G#",
    root: "E",
    quality: "maj",
    tension: "7",
    bass: "G#",
    description: "Emaj7 chord with G# as bass.",
  },
  {
    strings: "X 7 6 4 5 4",
    fingering: "X 4 3 1 2 1",
    chordName: "E,m,7,B",
    root: "E",
    quality: "m",
    tension: "7",
    bass: "B",
    description: "E minor 7th chord with B as bass.",
  },
  {
    strings: "X 7 9 7 9 7",
    fingering: "X 1 3 1 4 1",
    chordName: "E,m,,B",
    root: "E",
    quality: "m",
    tension: "",
    bass: "B",
    description: "E minor chord with B as bass.",
  },
  {
    strings: "X 7 6 4 5 4",
    fingering: "X 4 3 1 2 1",
    chordName: "E,m,7b5,G",
    root: "E",
    quality: "m",
    tension: "7b5",
    bass: "G",
    description: "E minor 7th flat 5 chord with G as bass.",
  },
  {
    strings: "X 7 9 9 8 7",
    fingering: "X 1 3 4 2 1",
    chordName: "E,,9,B",
    root: "E",
    quality: "",
    tension: "9",
    bass: "B",
    description: "E9 chord with B as bass.",
  },
  {
    strings: "X 7 9 8 9 7",
    fingering: "X 1 3 2 4 1",
    chordName: "E,,add11,C#",
    root: "E",
    quality: "",
    tension: "add11",
    bass: "C#",
    description: "E add11 chord with C# as bass.",
  },
  {
    strings: "X 7 9 9 7 7",
    fingering: "X 1 3 4 1 1",
    chordName: "E,,7sus4,A",
    root: "E",
    quality: "",
    tension: "7sus4",
    bass: "A",
    description: "E7sus4 chord with A as bass.",
  },
  {
    strings: "X 7 9 7 10 7",
    fingering: "X 1 3 1 4 1",
    chordName: "E,,7#5,G#",
    root: "E",
    quality: "",
    tension: "7#5",
    bass: "G#",
    description: "E7#5 chord with G# as bass.",
  },
  {
    strings: "X 7 6 4 4 4",
    fingering: "X 2 1 1 1 1",
    chordName: "E,m,7b5,C",
    root: "E",
    quality: "m",
    tension: "7b5",
    bass: "C",
    description: "E minor 7th flat 5 chord with C as bass.",
  },

  // F Chords
  {
    strings: "1 3 3 2 1 1",
    fingering: "1 3 4 2 1 1",
    chordName: "F,,,",
    root: "F",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard F major barre chord.",
  },
  {
    strings: "1 3 3 1 1 1",
    fingering: "1 3 4 1 1 1",
    chordName: "F,m,,",
    root: "F",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard F minor barre chord.",
  },
  {
    strings: "1 3 1 2 1 1",
    fingering: "1 3 1 2 1 1",
    chordName: "F,,7,",
    root: "F",
    quality: "",
    tension: "7",
    bass: "",
    description: "F7 chord, standard barre position.",
  },
  {
    strings: "1 3 2 2 1 1",
    fingering: "1 3 2 2 1 1",
    chordName: "F,maj,7,",
    root: "F",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Fmaj7 chord, barre position.",
  },
  {
    strings: "1 3 1 1 1 1",
    fingering: "1 3 1 1 1 1",
    chordName: "F,m,7,",
    root: "F",
    quality: "m",
    tension: "7",
    bass: "",
    description: "F minor 7th chord.",
  },
  {
    strings: "1 0 3 2 1 1",
    fingering: "1 0 4 3 2 1",
    chordName: "F,,add9,",
    root: "F",
    quality: "",
    tension: "add9",
    bass: "",
    description: "F add9 chord.",
  },
  {
    strings: "1 X 3 2 1 0",
    fingering: "1 X 3 2 1 0",
    chordName: "F,maj,9,",
    root: "F",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "F major 9th chord.",
  },
  {
    strings: "1 3 3 2 3 1",
    fingering: "1 3 3 2 4 1",
    chordName: "F,,,C",
    root: "F",
    quality: "",
    tension: "",
    bass: "C",
    description: "F major chord with C as bass note.",
  },
  {
    strings: "1 3 3 1 3 1",
    fingering: "1 3 3 1 4 1",
    chordName: "F,m,,C",
    root: "F",
    quality: "m",
    tension: "",
    bass: "C",
    description: "F minor chord with C as bass note.",
  },
  {
    strings: "X X 3 2 1 1",
    fingering: "X X 3 2 1 1",
    chordName: "F,,7sus4,",
    root: "F",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "F7sus4 chord.",
  },
  {
    strings: "X X 3 2 1 3",
    fingering: "X X 3 2 1 4",
    chordName: "F,,6,",
    root: "F",
    quality: "",
    tension: "6",
    bass: "",
    description: "F6 chord.",
  },
  {
    strings: "8 10 10 9 8 8",
    fingering: "1 3 4 2 1 1",
    chordName: "F,,,F",
    root: "F",
    quality: "",
    tension: "",
    bass: "F",
    description: "F major barre chord at the 8th fret with F as bass.",
  },
  {
    strings: "8 10 10 8 8 8",
    fingering: "1 3 4 1 1 1",
    chordName: "F,m,,F",
    root: "F",
    quality: "m",
    tension: "",
    bass: "F",
    description: "F minor barre chord at the 8th fret with F as bass.",
  },
  {
    strings: "X X 3 2 3 3",
    fingering: "X X 1 2 3 4",
    chordName: "F,,6/9,",
    root: "F",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "F6/9 chord.",
  },
  {
    strings: "X 8 7 5 6 5",
    fingering: "X 4 3 1 2 1",
    chordName: "F,maj,7,",
    root: "F",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Fmaj7 chord with alternative voicing.",
  },
  {
    strings: "X X 3 2 1 3",
    fingering: "X X 3 2 1 4",
    chordName: "F,,add11,",
    root: "F",
    quality: "",
    tension: "add11",
    bass: "",
    description: "F chord with an added 11th.",
  },
  {
    strings: "X X 3 1 1 1",
    fingering: "X X 3 1 1 1",
    chordName: "F,m,,G",
    root: "F",
    quality: "m",
    tension: "",
    bass: "G",
    description: "F minor chord with G as bass.",
  },
  {
    strings: "X X 8 10 10 9",
    fingering: "X X 1 3 4 2",
    chordName: "F,,9,A",
    root: "F",
    quality: "",
    tension: "9",
    bass: "A",
    description: "F9 chord with A as bass.",
  },
  {
    strings: "X 8 7 0 6 0",
    fingering: "X 4 3 0 2 0",
    chordName: "F,maj,7b5,B",
    root: "F",
    quality: "maj",
    tension: "7b5",
    bass: "B",
    description: "Fmaj7 chord with flat fifth and B as bass.",
  },
  {
    strings: "X X 3 5 5 5",
    fingering: "X X 1 3 4 4",
    chordName: "F,,6/9,C",
    root: "F",
    quality: "",
    tension: "6/9",
    bass: "C",
    description: "F6/9 chord with C as bass.",
  },

  // F# Chords
  {
    strings: "2 4 4 3 2 2",
    fingering: "1 3 4 2 1 1",
    chordName: "F#,,,",
    root: "F#",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard F# major barre chord.",
  },
  {
    strings: "2 4 4 2 2 2",
    fingering: "1 3 4 1 1 1",
    chordName: "F#,m,,",
    root: "F#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard F# minor barre chord.",
  },
  {
    strings: "2 4 2 3 2 2",
    fingering: "1 3 1 2 1 1",
    chordName: "F#,,7,",
    root: "F#",
    quality: "",
    tension: "7",
    bass: "",
    description: "F#7 chord, barre position.",
  },
  {
    strings: "2 4 3 3 2 2",
    fingering: "1 3 2 2 1 1",
    chordName: "F#,maj,7,",
    root: "F#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "F#maj7 chord, barre position.",
  },
  {
    strings: "2 4 2 2 2 2",
    fingering: "1 3 1 1 1 1",
    chordName: "F#,m,7,",
    root: "F#",
    quality: "m",
    tension: "7",
    bass: "",
    description: "F# minor 7th chord.",
  },
  {
    strings: "2 X 4 3 2 2",
    fingering: "1 X 4 3 2 1",
    chordName: "F#,,add9,",
    root: "F#",
    quality: "",
    tension: "add9",
    bass: "",
    description: "F# add9 chord.",
  },
  {
    strings: "2 X 4 3 2 4",
    fingering: "1 X 3 2 1 4",
    chordName: "F#,maj,9,",
    root: "F#",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "F# major 9th chord.",
  },
  {
    strings: "2 4 4 3 4 2",
    fingering: "1 3 4 2 4 1",
    chordName: "F#,,,C#",
    root: "F#",
    quality: "",
    tension: "",
    bass: "C#",
    description: "F# major chord with C# as bass note.",
  },
  {
    strings: "2 4 4 2 4 2",
    fingering: "1 3 3 1 4 1",
    chordName: "F#,m,,C#",
    root: "F#",
    quality: "m",
    tension: "",
    bass: "C#",
    description: "F# minor chord with C# as bass note.",
  },
  {
    strings: "X X 4 3 2 0",
    fingering: "X X 4 3 2 0",
    chordName: "F#,,7sus4,",
    root: "F#",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "F#7sus4 chord.",
  },
  {
    strings: "X X 4 3 2 2",
    fingering: "X X 4 3 2 1",
    chordName: "F#,,6,",
    root: "F#",
    quality: "",
    tension: "6",
    bass: "",
    description: "F#6 chord.",
  },
  {
    strings: "9 11 11 10 9 9",
    fingering: "1 3 4 2 1 1",
    chordName: "F#,,,F#",
    root: "F#",
    quality: "",
    tension: "",
    bass: "F#",
    description: "F# major barre chord at the 9th fret with F# as bass.",
  },
  {
    strings: "9 11 11 9 9 9",
    fingering: "1 3 4 1 1 1",
    chordName: "F#,m,,F#",
    root: "F#",
    quality: "m",
    tension: "",
    bass: "F#",
    description: "F# minor barre chord at the 9th fret with F# as bass.",
  },
  {
    strings: "X X 4 3 4 4",
    fingering: "X X 1 2 3 4",
    chordName: "F#,,6/9,",
    root: "F#",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "F#6/9 chord.",
  },
  {
    strings: "X 9 8 6 7 6",
    fingering: "X 4 3 1 2 1",
    chordName: "F#,maj,7,",
    root: "F#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "F#maj7 chord with alternative voicing.",
  },
  {
    strings: "X X 4 3 2 4",
    fingering: "X X 3 2 1 4",
    chordName: "F#,,add11,",
    root: "F#",
    quality: "",
    tension: "add11",
    bass: "",
    description: "F# chord with an added 11th.",
  },
  {
    strings: "X X 11 10 9 9",
    fingering: "X X 3 2 1 1",
    chordName: "F#,m,,G",
    root: "F#",
    quality: "m",
    tension: "",
    bass: "G",
    description: "F# minor chord with high voicing and G as bass.",
  },
  {
    strings: "X X 11 13 14 13",
    fingering: "X X 1 3 4 2",
    chordName: "F#,,9,A",
    root: "F#",
    quality: "",
    tension: "9",
    bass: "A",
    description: "F#9 chord with A as bass.",
  },
  {
    strings: "X 9 8 0 7 0",
    fingering: "X 4 3 0 2 0",
    chordName: "F#,maj,7b5,B",
    root: "F#",
    quality: "maj",
    tension: "7b5",
    bass: "B",
    description: "F#maj7 chord with flat fifth and B as bass.",
  },
  {
    strings: "X X 4 6 6 6",
    fingering: "X X 1 3 4 4",
    chordName: "F#,,6/9,C#",
    root: "F#",
    quality: "",
    tension: "6/9",
    bass: "C#",
    description: "F#6/9 chord with C# as bass.",
  },

  // G Chords
  {
    strings: "3 2 0 0 0 3",
    fingering: "2 1 0 0 0 3",
    chordName: "G,,,",
    root: "G",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard G major chord.",
  },
  {
    strings: "3 1 0 0 0 3",
    fingering: "2 1 0 0 0 4",
    chordName: "G,m,,",
    root: "G",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard G minor chord.",
  },
  {
    strings: "3 2 0 0 0 1",
    fingering: "2 1 0 0 0 1",
    chordName: "G,,7,",
    root: "G",
    quality: "",
    tension: "7",
    bass: "",
    description: "G7 chord, open position.",
  },
  {
    strings: "3 2 0 0 0 2",
    fingering: "2 1 0 0 0 3",
    chordName: "G,maj,7,",
    root: "G",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Gmaj7 chord, open position.",
  },
  {
    strings: "3 1 0 3 3 3",
    fingering: "2 1 0 4 3 4",
    chordName: "G,m,7,",
    root: "G",
    quality: "m",
    tension: "7",
    bass: "",
    description: "G minor 7th chord.",
  },
  {
    strings: "3 2 0 2 0 3",
    fingering: "2 1 0 3 0 4",
    chordName: "G,,add9,",
    root: "G",
    quality: "",
    tension: "add9",
    bass: "",
    description: "G add9 chord.",
  },
  {
    strings: "3 X 0 2 0 2",
    fingering: "2 X 0 3 0 4",
    chordName: "G,maj,9,",
    root: "G",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "G major 9th chord.",
  },
  {
    strings: "3 2 0 0 3 3",
    fingering: "2 1 0 0 3 4",
    chordName: "G,,,D",
    root: "G",
    quality: "",
    tension: "",
    bass: "D",
    description: "G major chord with D as bass note.",
  },
  {
    strings: "3 1 0 0 3 3",
    fingering: "2 1 0 0 3 4",
    chordName: "G,m,,D",
    root: "G",
    quality: "m",
    tension: "",
    bass: "D",
    description: "G minor chord with D as bass note.",
  },
  {
    strings: "X 2 0 0 3 1",
    fingering: "X 1 0 0 3 1",
    chordName: "G,,7sus4,",
    root: "G",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "G7sus4 chord.",
  },
  {
    strings: "X X 0 4 0 3",
    fingering: "X X 0 2 0 1",
    chordName: "G,,6,",
    root: "G",
    quality: "",
    tension: "6",
    bass: "",
    description: "G6 chord, open position.",
  },
  {
    strings: "10 12 12 11 10 10",
    fingering: "1 3 4 2 1 1",
    chordName: "G,,,G",
    root: "G",
    quality: "",
    tension: "",
    bass: "G",
    description: "G major barre chord at the 10th fret with G as bass.",
  },
  {
    strings: "10 12 12 10 10 10",
    fingering: "1 3 4 1 1 1",
    chordName: "G,m,,G",
    root: "G",
    quality: "m",
    tension: "",
    bass: "G",
    description: "G minor barre chord at the 10th fret with G as bass.",
  },
  {
    strings: "X X 0 2 2 2",
    fingering: "X X 1 2 3 4",
    chordName: "G,,6/9,",
    root: "G",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "G6/9 chord.",
  },
  {
    strings: "X 5 4 2 3 2",
    fingering: "X 4 3 1 2 1",
    chordName: "G,maj,7,",
    root: "G",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Gmaj7 chord with alternative voicing.",
  },
  {
    strings: "X X 0 2 0 3",
    fingering: "X X 1 2 0 4",
    chordName: "G,,add11,",
    root: "G",
    quality: "",
    tension: "add11",
    bass: "",
    description: "G chord with an added 11th.",
  },
  {
    strings: "X X 12 11 10 10",
    fingering: "X X 3 2 1 1",
    chordName: "G,m,,A",
    root: "G",
    quality: "m",
    tension: "",
    bass: "A",
    description: "G minor chord with high voicing and A as bass.",
  },
  {
    strings: "X X 12 14 15 14",
    fingering: "X X 1 3 4 2",
    chordName: "G,,9,B",
    root: "G",
    quality: "",
    tension: "9",
    bass: "B",
    description: "G9 chord, high voicing with B as bass.",
  },
  {
    strings: "X 5 4 0 3 0",
    fingering: "X 4 3 0 2 0",
    chordName: "G,maj,7b5,D",
    root: "G",
    quality: "maj",
    tension: "7b5",
    bass: "D",
    description: "Gmaj7 chord with flat fifth and D as bass.",
  },
  {
    strings: "X X 0 2 4 5",
    fingering: "X X 1 2 4 5",
    chordName: "G,,6/9,E",
    root: "G",
    quality: "",
    tension: "6/9",
    bass: "E",
    description: "G6/9 chord with E as bass.",
  },

  // G# Chords
  {
    strings: "4 6 6 5 4 4",
    fingering: "1 3 4 2 1 1",
    chordName: "G#,,,",
    root: "G#",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard G# major barre chord.",
  },
  {
    strings: "4 6 6 4 4 4",
    fingering: "1 3 4 1 1 1",
    chordName: "G#,m,,",
    root: "G#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard G# minor barre chord.",
  },
  {
    strings: "4 6 4 5 4 4",
    fingering: "1 3 1 2 1 1",
    chordName: "G#,,7,",
    root: "G#",
    quality: "",
    tension: "7",
    bass: "",
    description: "G#7 chord, barre position.",
  },
  {
    strings: "4 6 5 5 4 4",
    fingering: "1 3 2 2 1 1",
    chordName: "G#,maj,7,",
    root: "G#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "G#maj7 chord, barre position.",
  },
  {
    strings: "4 6 4 4 4 4",
    fingering: "1 3 1 1 1 1",
    chordName: "G#,m,7,",
    root: "G#",
    quality: "m",
    tension: "7",
    bass: "",
    description: "G# minor 7th chord.",
  },
  {
    strings: "4 X 6 5 4 4",
    fingering: "1 X 4 3 2 1",
    chordName: "G#,,add9,",
    root: "G#",
    quality: "",
    tension: "add9",
    bass: "",
    description: "G# add9 chord.",
  },
  {
    strings: "4 X 6 5 4 6",
    fingering: "1 X 3 2 1 4",
    chordName: "G#,maj,9,",
    root: "G#",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "G# major 9th chord.",
  },
  {
    strings: "4 6 6 5 6 4",
    fingering: "1 3 4 2 4 1",
    chordName: "G#,,,D#",
    root: "G#",
    quality: "",
    tension: "",
    bass: "D#",
    description: "G# major chord with D# as bass note.",
  },
  {
    strings: "4 6 6 4 6 4",
    fingering: "1 3 3 1 4 1",
    chordName: "G#,m,,D#",
    root: "G#",
    quality: "m",
    tension: "",
    bass: "D#",
    description: "G# minor chord with D# as bass note.",
  },
  {
    strings: "X X 6 5 4 4",
    fingering: "X X 4 3 2 1",
    chordName: "G#,,7sus4,",
    root: "G#",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "G#7sus4 chord.",
  },
  {
    strings: "X X 6 5 4 6",
    fingering: "X X 2 1 1 4",
    chordName: "G#,,6,",
    root: "G#",
    quality: "",
    tension: "6",
    bass: "",
    description: "G#6 chord, open position.",
  },
  {
    strings: "11 13 13 12 11 11",
    fingering: "1 3 4 2 1 1",
    chordName: "G#,,,G#",
    root: "G#",
    quality: "",
    tension: "",
    bass: "G#",
    description: "G# major barre chord at the 11th fret with G# as bass.",
  },
  {
    strings: "11 13 13 11 11 11",
    fingering: "1 3 4 1 1 1",
    chordName: "G#,m,,G#",
    root: "G#",
    quality: "m",
    tension: "",
    bass: "G#",
    description: "G# minor barre chord at the 11th fret with G# as bass.",
  },
  {
    strings: "X X 6 8 8 8",
    fingering: "X X 1 3 4 4",
    chordName: "G#,,6/9,",
    root: "G#",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "G#6/9 chord.",
  },
  {
    strings: "X 11 10 8 9 8",
    fingering: "X 4 3 1 2 1",
    chordName: "G#,maj,7,",
    root: "G#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "G#maj7 chord with alternative voicing.",
  },
  {
    strings: "X X 6 5 4 6",
    fingering: "X X 3 2 1 4",
    chordName: "G#,,add11,",
    root: "G#",
    quality: "",
    tension: "add11",
    bass: "",
    description: "G# chord with an added 11th.",
  },
  {
    strings: "X X 13 12 11 11",
    fingering: "X X 3 2 1 1",
    chordName: "G#,m,,A",
    root: "G#",
    quality: "m",
    tension: "",
    bass: "A",
    description: "G# minor chord with high voicing and A as bass.",
  },
  {
    strings: "X X 13 15 16 15",
    fingering: "X X 1 3 4 2",
    chordName: "G#,,9,B",
    root: "G#",
    quality: "",
    tension: "9",
    bass: "B",
    description: "G#9 chord, high voicing with B as bass.",
  },
  {
    strings: "X 11 10 0 9 0",
    fingering: "X 4 3 0 2 0",
    chordName: "G#,maj,7b5,D",
    root: "G#",
    quality: "maj",
    tension: "7b5",
    bass: "D",
    description: "G#maj7 chord with flat fifth and D as bass.",
  },
  {
    strings: "X X 6 8 9 9",
    fingering: "X X 1 3 4 4",
    chordName: "G#,,6/9,F",
    root: "G#",
    quality: "",
    tension: "6/9",
    bass: "F",
    description: "G#6/9 chord with F as bass.",
  },

  // A Chords
  {
    strings: "X 0 2 2 2 0",
    fingering: "X 0 1 2 3 0",
    chordName: "A,,,",
    root: "A",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard A major chord.",
  },
  {
    strings: "X 0 2 2 1 0",
    fingering: "X 0 2 3 1 0",
    chordName: "A,m,,",
    root: "A",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard A minor chord.",
  },
  {
    strings: "X 0 2 0 2 0",
    fingering: "X 0 2 0 3 0",
    chordName: "A,,7,",
    root: "A",
    quality: "",
    tension: "7",
    bass: "",
    description: "A7 chord, open position.",
  },
  {
    strings: "X 0 2 1 2 0",
    fingering: "X 0 2 1 3 0",
    chordName: "A,maj,7,",
    root: "A",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Amaj7 chord, open position.",
  },
  {
    strings: "X 0 2 0 1 0",
    fingering: "X 0 2 0 1 0",
    chordName: "A,m,7,",
    root: "A",
    quality: "m",
    tension: "7",
    bass: "",
    description: "A minor 7th chord.",
  },
  {
    strings: "X 0 2 4 2 0",
    fingering: "X 0 1 4 2 0",
    chordName: "A,,add9,",
    root: "A",
    quality: "",
    tension: "add9",
    bass: "",
    description: "A add9 chord.",
  },
  {
    strings: "X 0 2 1 2 4",
    fingering: "X 0 2 1 3 4",
    chordName: "A,maj,9,",
    root: "A",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "A major 9th chord.",
  },
  {
    strings: "X 0 2 2 2 4",
    fingering: "X 0 1 2 3 4",
    chordName: "A,,,E",
    root: "A",
    quality: "",
    tension: "",
    bass: "E",
    description: "A major chord with E as bass note.",
  },
  {
    strings: "X 0 2 2 1 4",
    fingering: "X 0 2 3 1 4",
    chordName: "A,m,,E",
    root: "A",
    quality: "m",
    tension: "",
    bass: "E",
    description: "A minor chord with E as bass note.",
  },
  {
    strings: "X 0 2 0 3 0",
    fingering: "X 0 1 0 3 0",
    chordName: "A,,7sus4,",
    root: "A",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "A7sus4 chord.",
  },
  {
    strings: "X 0 2 2 2 2",
    fingering: "X 0 1 2 3 4",
    chordName: "A,,6,",
    root: "A",
    quality: "",
    tension: "6",
    bass: "",
    description: "A6 chord, open position.",
  },
  {
    strings: "5 7 7 6 5 5",
    fingering: "1 3 4 2 1 1",
    chordName: "A,,,A",
    root: "A",
    quality: "",
    tension: "",
    bass: "A",
    description: "A major barre chord at the 5th fret with A as bass.",
  },
  {
    strings: "5 7 7 5 5 5",
    fingering: "1 3 4 1 1 1",
    chordName: "A,m,,A",
    root: "A",
    quality: "m",
    tension: "",
    bass: "A",
    description: "A minor barre chord at the 5th fret with A as bass.",
  },
  {
    strings: "X 0 2 4 4 4",
    fingering: "X 0 1 3 4 4",
    chordName: "A,,6/9,",
    root: "A",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "A6/9 chord.",
  },
  {
    strings: "X 0 1 1 2 0",
    fingering: "X 0 1 1 2 0",
    chordName: "A,maj,7,",
    root: "A",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Amaj7 chord with alternative voicing.",
  },
  {
    strings: "X 0 2 2 0 4",
    fingering: "X 0 1 2 0 4",
    chordName: "A,,add11,",
    root: "A",
    quality: "",
    tension: "add11",
    bass: "",
    description: "A chord with an added 11th.",
  },
  {
    strings: "X X 7 6 5 5",
    fingering: "X X 3 2 1 1",
    chordName: "A,m,,B",
    root: "A",
    quality: "m",
    tension: "",
    bass: "B",
    description: "A minor chord with high voicing and B as bass.",
  },
  {
    strings: "X X 7 9 10 9",
    fingering: "X X 1 3 4 2",
    chordName: "A,,9,C#",
    root: "A",
    quality: "",
    tension: "9",
    bass: "C#",
    description: "A9 chord, high voicing with C# as bass.",
  },
  {
    strings: "X 0 1 0 2 0",
    fingering: "X 0 1 0 2 0",
    chordName: "A,maj,7b5,F#",
    root: "A",
    quality: "maj",
    tension: "7b5",
    bass: "F#",
    description: "Amaj7 chord with flat fifth and F# as bass.",
  },
  {
    strings: "X X 0 4 4 5",
    fingering: "X X 1 3 4 5",
    chordName: "A,,6/9,G",
    root: "A",
    quality: "",
    tension: "6/9",
    bass: "G",
    description: "A6/9 chord with G as bass.",
  },

  // A#
  {
    strings: "X 1 3 3 3 1",
    fingering: "X 1 3 4 4 1",
    chordName: "A#,,,",
    root: "A#",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard A# major barre chord.",
  },
  {
    strings: "X 1 3 3 2 1",
    fingering: "X 1 3 4 2 1",
    chordName: "A#,m,,",
    root: "A#",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard A# minor barre chord.",
  },
  {
    strings: "X 1 3 1 3 1",
    fingering: "X 1 3 1 4 1",
    chordName: "A#,,7,",
    root: "A#",
    quality: "",
    tension: "7",
    bass: "",
    description: "A#7 chord, barre position.",
  },
  {
    strings: "X 1 3 2 3 1",
    fingering: "X 1 3 2 4 1",
    chordName: "A#,maj,7,",
    root: "A#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "A#maj7 chord, barre position.",
  },
  {
    strings: "X 1 3 1 2 1",
    fingering: "X 1 3 1 2 1",
    chordName: "A#,m,7,",
    root: "A#",
    quality: "m",
    tension: "7",
    bass: "",
    description: "A# minor 7th chord.",
  },
  {
    strings: "X 1 3 0 3 1",
    fingering: "X 1 3 0 4 1",
    chordName: "A#,,add9,",
    root: "A#",
    quality: "",
    tension: "add9",
    bass: "",
    description: "A# add9 chord.",
  },
  {
    strings: "X 1 3 2 3 4",
    fingering: "X 1 3 2 4 4",
    chordName: "A#,maj,9,",
    root: "A#",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "A# major 9th chord.",
  },
  {
    strings: "6 8 8 7 6 6",
    fingering: "1 3 4 2 1 1",
    chordName: "A#,,,A#",
    root: "A#",
    quality: "",
    tension: "",
    bass: "A#",
    description: "A# major barre chord at the 6th fret with A# as bass.",
  },
  {
    strings: "6 8 8 6 6 6",
    fingering: "1 3 4 1 1 1",
    chordName: "A#,m,,A#",
    root: "A#",
    quality: "m",
    tension: "",
    bass: "A#",
    description: "A# minor barre chord at the 6th fret with A# as bass.",
  },
  {
    strings: "X 1 3 1 4 1",
    fingering: "X 1 3 1 4 1",
    chordName: "A#,m,,F",
    root: "A#",
    quality: "m",
    tension: "",
    bass: "F",
    description: "A# minor chord with F as bass note.",
  },
  {
    strings: "X X 8 7 6 6",
    fingering: "X X 4 3 2 1",
    chordName: "A#,,7sus4,",
    root: "A#",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "A#7sus4 chord.",
  },
  {
    strings: "X X 8 7 6 8",
    fingering: "X X 2 1 1 4",
    chordName: "A#,,6,",
    root: "A#",
    quality: "",
    tension: "6",
    bass: "",
    description: "A#6 chord, open position.",
  },
  {
    strings: "6 8 8 6 8 6",
    fingering: "1 3 3 1 4 1",
    chordName: "A#,m,7,A#",
    root: "A#",
    quality: "m",
    tension: "7",
    bass: "A#",
    description: "A# minor 7th chord with A# as bass.",
  },
  {
    strings: "X X 8 10 10 10",
    fingering: "X X 1 3 4 4",
    chordName: "A#,,6/9,",
    root: "A#",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "A#6/9 chord.",
  },
  {
    strings: "X 1 0 2 3 2",
    fingering: "X 1 0 2 3 2",
    chordName: "A#,maj,7,",
    root: "A#",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "A#maj7 chord with alternative voicing.",
  },
  {
    strings: "X 1 3 3 1 4",
    fingering: "X 1 3 4 1 4",
    chordName: "A#,,add11,",
    root: "A#",
    quality: "",
    tension: "add11",
    bass: "",
    description: "A# chord with an added 11th.",
  },
  {
    strings: "X X 8 7 6 7",
    fingering: "X X 3 2 1 2",
    chordName: "A#,m,,C",
    root: "A#",
    quality: "m",
    tension: "",
    bass: "C",
    description: "A# minor chord with C as bass.",
  },
  {
    strings: "X X 8 10 11 10",
    fingering: "X X 1 3 4 2",
    chordName: "A#,,9,D",
    root: "A#",
    quality: "",
    tension: "9",
    bass: "D",
    description: "A#9 chord, high voicing with D as bass.",
  },
  {
    strings: "X 1 0 1 2 1",
    fingering: "X 1 0 1 2 1",
    chordName: "A#,maj,7b5,F",
    root: "A#",
    quality: "maj",
    tension: "7b5",
    bass: "F",
    description: "A#maj7 chord with flat fifth and F as bass.",
  },
  {
    strings: "X X 8 10 11 12",
    fingering: "X X 1 3 4 5",
    chordName: "A#,,6/9,G",
    root: "A#",
    quality: "",
    tension: "6/9",
    bass: "G",
    description: "A#6/9 chord with G as bass.",
  },

  // B chords

  {
    strings: "X 2 4 4 4 2",
    fingering: "X 1 3 4 4 1",
    chordName: "B,,,",
    root: "B",
    quality: "",
    tension: "",
    bass: "",
    description: "Standard B major barre chord.",
  },
  {
    strings: "X 2 4 4 3 2",
    fingering: "X 1 3 4 2 1",
    chordName: "B,m,,",
    root: "B",
    quality: "m",
    tension: "",
    bass: "",
    description: "Standard B minor barre chord.",
  },
  {
    strings: "X 2 1 2 0 2",
    fingering: "X 2 1 3 0 4",
    chordName: "B,,7,",
    root: "B",
    quality: "",
    tension: "7",
    bass: "",
    description: "B7 chord, open position.",
  },
  {
    strings: "X 2 4 3 4 2",
    fingering: "X 1 3 2 4 1",
    chordName: "B,maj,7,",
    root: "B",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Bmaj7 chord, barre position.",
  },
  {
    strings: "X 2 0 2 0 2",
    fingering: "X 1 0 2 0 3",
    chordName: "B,m,7,",
    root: "B",
    quality: "m",
    tension: "7",
    bass: "",
    description: "B minor 7th chord.",
  },
  {
    strings: "X 2 4 1 4 2",
    fingering: "X 1 4 1 3 2",
    chordName: "B,,add9,",
    root: "B",
    quality: "",
    tension: "add9",
    bass: "",
    description: "B add9 chord.",
  },
  {
    strings: "X 2 4 3 4 4",
    fingering: "X 1 3 2 4 4",
    chordName: "B,maj,9,",
    root: "B",
    quality: "maj",
    tension: "9",
    bass: "",
    description: "B major 9th chord.",
  },
  {
    strings: "7 9 9 8 7 7",
    fingering: "1 3 4 2 1 1",
    chordName: "B,,,B",
    root: "B",
    quality: "",
    tension: "",
    bass: "B",
    description: "B major barre chord at the 7th fret with B as bass.",
  },
  {
    strings: "7 9 9 7 7 7",
    fingering: "1 3 4 1 1 1",
    chordName: "B,m,,B",
    root: "B",
    quality: "m",
    tension: "",
    bass: "B",
    description: "B minor barre chord at the 7th fret with B as bass.",
  },
  {
    strings: "X 2 4 2 5 2",
    fingering: "X 1 3 1 4 1",
    chordName: "B,,7sus4,",
    root: "B",
    quality: "",
    tension: "7sus4",
    bass: "",
    description: "B7sus4 chord.",
  },
  {
    strings: "X 2 4 1 0 2",
    fingering: "X 1 3 1 0 4",
    chordName: "B,,6,",
    root: "B",
    quality: "",
    tension: "6",
    bass: "",
    description: "B6 chord, open position.",
  },
  {
    strings: "7 9 9 7 9 7",
    fingering: "1 3 3 1 4 1",
    chordName: "B,m,7,B",
    root: "B",
    quality: "m",
    tension: "7",
    bass: "B",
    description: "B minor 7th chord with B as bass.",
  },
  {
    strings: "X X 9 8 7 7",
    fingering: "X X 4 3 2 1",
    chordName: "B,,6/9,",
    root: "B",
    quality: "",
    tension: "6/9",
    bass: "",
    description: "B6/9 chord.",
  },
  {
    strings: "X 2 1 1 3 2",
    fingering: "X 2 1 1 3 2",
    chordName: "B,maj,7,",
    root: "B",
    quality: "maj",
    tension: "7",
    bass: "",
    description: "Bmaj7 chord with alternative voicing.",
  },
  {
    strings: "X 2 4 4 2 5",
    fingering: "X 1 3 4 1 4",
    chordName: "B,,add11,",
    root: "B",
    quality: "",
    tension: "add11",
    bass: "",
    description: "B chord with an added 11th.",
  },
  {
    strings: "X X 9 8 7 8",
    fingering: "X X 3 2 1 2",
    chordName: "B,m,,C#",
    root: "B",
    quality: "m",
    tension: "",
    bass: "C#",
    description: "B minor chord with C# as bass.",
  },
  {
    strings: "X X 9 11 12 11",
    fingering: "X X 1 3 4 2",
    chordName: "B,,9,D#",
    root: "B",
    quality: "",
    tension: "9",
    bass: "D#",
    description: "B9 chord, high voicing with D# as bass.",
  },
  {
    strings: "X 2 1 0 3 0",
    fingering: "X 2 1 0 3 0",
    chordName: "B,maj,7b5,F#",
    root: "B",
    quality: "maj",
    tension: "7b5",
    bass: "F#",
    description: "Bmaj7 chord with flat fifth and F# as bass.",
  },
  {
    strings: "X X 9 11 12 14",
    fingering: "X X 1 3 4 5",
    chordName: "B,,6/9,G",
    root: "B",
    quality: "",
    tension: "6/9",
    bass: "G",
    description: "B6/9 chord with G as bass.",
  },
];
